/*
 * This source file was generated by the Gradle 'init' task
 */
package oop;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

     public static void main(String[] args) {
        BankAccount account = new BankAccount(500.0);
        System.out.println("Initial Balance: " + account.getBalance());
        account.deposit(150.0);
        System.out.println("After Deposit: " + account.getBalance());
        account.withdraw(100.0);
        System.out.println("After Withdrawal: " + account.getBalance());
    }
}
