/*
 * This source file was generated by the Gradle 'init' task
 */
package oop.polymorphism;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Payment payment1 = new CashPayment();
        payment1.pay(100); // Output: Paid 100 using cash.
        System.out.println("Payment Type:" + payment1.paymentType);
        Payment payment2 = new CreditPayment();
        payment2.pay(200); // Output: Paid 200 using credit card.
        System.out.println("Payment Type:" + payment2.paymentType);
    }
}
